apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: ghcr.io/holgers66/argocd-docker:main@sha256:43880bf9fd1dadd778358d3f1de57bea121240418bf82a473353782df1503d76
        name: flaskdemo
        resources: {}
status: {}
