apiVersion: v1
kind: Service
metadata:
  name: flask-lb-svc
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: flaskdemo
  ports:
   — protocol: TCP
     port: 80
     targetPort: 5000
